name: Deploy to production

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [main]

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on:
      group: Default
      labels: [self-hosted, linux, x64]
    steps:
      - name: Download build artifact from triggered workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: frontend-artifact
          path: /tmp/frontend-artifact
          search_artifacts: true
      - name: Deploy to production
        run: |
          cd /tmp/frontend-artifact/frontend-payload
          ./server_deploy.sh ${{ github.event.repository.name }} /tmp/frontend-artifact/frontend-payload prod
