name: Node CI

on: [push]

jobs:
  security-check:
    runs-on: [ubuntu-latest]
    steps:
      - name: Snyk
        uses: snyk/actions@0.1.1
          
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd ./homepage
        git submodule update --init --recursive
        npm ci
        npm run build
      env:
        CI: true

    - name: Upload build output
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: dist-homepage
        # Directory containing files to upload
        path: homepage/dist/homepage
